apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "argocd-tech-adapter.name" . }}
{{- include "argocd-tech-adapter.labels" . | nindent 4 }}
  name: {{ template "argocd-tech-adapter.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "argocd-tech-adapter.name" . }}
  template:
    metadata:
      annotations:
      labels:
        app: {{ template "argocd-tech-adapter.name" . }}
{{- include "argocd-tech-adapter.labels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      {{- if .Values.dockerRegistrySecretName }}
      imagePullSecrets:
        - name: {{ .Values.dockerRegistrySecretName }}
      {{- end}}
      volumes:
        - name: config
          configMap:
            name: {{ template "argocd-tech-adapter.fullname" . }}-config
            defaultMode: 420
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.registry }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          {{- if .Values.securityContext }}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe: {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe: {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ARGOCD_BASE_PATH
              valueFrom:
                secretKeyRef:
                  name: argocd-addons-secrets
                  key: ARGOCD_BASE_PATH
            - name: ARGOCD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argocd-addons-secrets
                  key: ARGOCD_TOKEN
            - name: ARGOCD_TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: argocd-addons-secrets
                  key: ARGOCD_TRUSTSTORE_PASSWORD
            - name: ARGOCD_TRUSTSTORE_PATH
              valueFrom:
                secretKeyRef:
                  name: argocd-addons-secrets
                  key: ARGOCD_TRUSTSTORE_PATH
            - name: GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argocd-addons-secrets
                  key: GIT_TOKEN
            - name: GIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: argocd-addons-secrets
                  key: GIT_USERNAME

            - name: SPRING_CONFIG_LOCATION
              value: file:/opt/docker/etc/configs/application.yml
            - name: OTEL_JAVAAGENT_ENABLED
              value: {{ quote .Values.otel.enabled }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.otel.collectorUrl }}
            - name: OTEL_METRICS_EXPORTER
              value: {{ .Values.otel.metricExporter }}
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.otel.serviceName }}
            - name: OTEL_TRACES_EXPORTER
              value: {{ .Values.otel.tracesExporter }}
            {{- if .Values.extraEnvVars }}
            {{- include "argocd-tech-adapter.tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /opt/docker/etc/configs
