apiVersion: v1
kind: Service
metadata:
  name: {{ template "argocd-tech-adapter.name" . }}
  labels:
{{- include "argocd-tech-adapter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "argocd-tech-adapter.name" . }}
