apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: witboost-addons-es
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: argocd-addons-secrets
  dataFrom:
    - extract:
        key: argocd-tech-adapter
