apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
        - key: "argocd-tech-adapter"
          valueMap:
            ARGOCD_BASE_PATH: https://fake-url:8080
            ARGOCD_TOKEN: fake-token
            ARGOCD_TRUSTSTORE_PASSWORD: fake-password
            ARGOCD_TRUSTSTORE_PATH: fake/path/truststore.jks
            GIT_TOKEN: git-token
            GIT_USERNAME: git-user
