spring:
  application:
    name: argocd-tech-adapter

server:
  port: 8888

springdoc:
  swagger-ui:
    path: /docs

argocd:
  token: ${ARGOCD_TOKEN}
  basePath: {$ARGOCD_BASE_PATH}

git:
  username: ${GIT_USERNAME}
  token: ${GIT_TOKEN}